app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, validators


class LoginForm(FlaskForm):
    username = StringField('Login')
    password = PasswordField('Password')
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
    post_title = StringField('Title', validators=[validators.Length(max=100, min=1)])
    post_public = BooleanField('Public')
    post_text = TextAreaField('Text', validators=[validators.Length(max=500, min=1)])
    post_submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment_text = TextAreaField('Text', validators=[validators.Length(max=250, min=1)])
    comment_id = StringField('ID');
    comment_submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_moment import Moment
from flask_redis import Redis
from flask_celery import Celery
from flask_sslify import SSLify

from config import config

moment = Moment()
redis_store = Redis()
celery = Celery()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    moment.init_app(app)
    redis_store.init_app(app)
    celery.init_app(app)

    sslify = SSLify(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, request, jsonify, session, redirect, url_for, get_template_attribute
from . import main
from .forms import LoginForm, PostForm, CommentForm
from .. import redis_store
from ..tasks import celery_render_recs, celery_post_recs, celery_post_comments
import requests
from datetime import datetime
from flask_moment import _moment


@main.route('/recs_async')
def recs_async():
    id = request.args.get('id')
    task = celery_render_recs.AsyncResult(id)
    if task.state != 'SUCCESS':
        return jsonify({'status': 'PROGRESS'})
    to_process = task.get()
    if not to_process:
        return jsonify({'status': 'EMPTY'})
    for ele in to_process:
        ele['timestamp'] = datetime.strptime(ele['timestamp'], '%a, %d %b %Y %X %Z')
    to_return = get_template_attribute('macros/render.html', 'render_recs')
    return jsonify({'status': 'SUCCESS', 'inject': to_return(to_process, _moment)})


@main.route('/recs_async_begin')
def recs_async_begin(page='', term='', user=''):
    if 'user' in session and redis_store.get(session['user']):
        page = str(page) or str(request.args.get('page', '1'))
        term = term or str(request.args.get('term', ''))
        user = user or str(request.args.get('user', ''))
        params = {'user': user, 'term': term}
        task = celery_render_recs.apply_async([redis_store.get(session['user']).decode('utf-8'), page, params])
        return task.id
    else:
        return -1


@main.route('/comments_get')
def comments_get():
    if 'user' in session and redis_store.get(session['user']):
        id = str(request.args.get('id'))
        session['id'] = id
        r = requests.get('https://rec-me.herokuapp.com/api1/recs/'+str(id)+'/comments/'+str(1),
                        auth=(redis_store.get(session['user']).decode('utf-8'),''))
        if r.status_code == 200:
            to_return = get_template_attribute('macros/render.html', 'render_comments')
            if not r.json().values():
                return jsonify({'status': 'EMPTY'})
            to_process = r.json().values()
            for ele in to_process:
                ele['timestamp'] = datetime.strptime(ele['timestamp'], '%a, %d %b %Y %X %Z')
            return jsonify({'status': 'SUCCESS', 'inject':
                to_return(sorted(to_process, key=lambda x: x['id'], reverse=True), _moment)})
        else:
            return jsonify({'status': 'FAILED'})


@main.route('/post_comments', methods=['POST'])
def post_comments():
    comment_form = CommentForm(request.form)
    if comment_form.validate():
        text = comment_form.comment_text.data
        id = comment_form.comment_id.data
        celery_post_comments.apply_async([redis_store.get(session['user']).decode('utf-8'), text, id])
        to_return = get_template_attribute('macros/render.html', 'render_comment')
        to_render = {'author_username': session['user'], 'text': text, 'timestamp': datetime.utcnow()}
        return jsonify({'status': 'SUCCESS', 'inject': to_return(to_render, _moment), 'id': id})
    return jsonify({'status': 'FAILURE'})


@main.route('/post_recs', methods=['POST'])
def post_recs():
    post_form = PostForm(request.form)
    if post_form.validate():
        title = post_form.post_title.data
        text = post_form.post_text.data
        public = 'True' if post_form.post_public.data else 'False'
        celery_post_recs.apply_async([redis_store.get(session['user']).decode('utf-8'), title, text, public])
        return jsonify({'status': 'SUCCESS'})
    return jsonify({'status': 'FAILURE'})


@main.route('/logout')
def logout():
    if 'user' in session:
        redis_store.dump(session['user'])
    session.clear()
    return redirect(url_for('main.index'))


@main.route('/login', methods=['POST'])
def login():
    login_form = LoginForm(request.form)
    if login_form.validate():
        user = login_form.username.data.lower()
        password = login_form.password.data
        r = requests.get('https://rec-me.herokuapp.com/api1/token/new', auth=(user, password))
        if r.status_code == 200:
            session['user'] = user
            redis_store.set(user, r.json()['token'], 3600)
            return jsonify({'status': 'SUCCESS', 'id': recs_async_begin(user=user)})
    return jsonify({'status': 'FAILURE'})


@main.route('/')
def index():
    login_form = LoginForm(request.form)
    post_form = PostForm(request.form)
    comment_form = CommentForm(request.form)
    id = recs_async_begin(user=session['user']) if 'user' in session else -1
    return render_template('main/index.html', login_form=login_form, post_form=post_form,
                           comment_form=comment_form, id=id)

app/templates/macros/modals.html
{% macro login(login_form) %}
  <div class="modal fade" id="login-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-title">
            Login
          </div>
        </div>
        <div class="modal-body">
          <form method="POST">
            <div class="form-group">
              <div class="input-group input-group-lg col-xs-10 col-xs-offset-1 has-feedback" data-toggle='tooltip'
                        data-placement='bottom' data-trigger='manual' title='Must be 5 characters or more'>
                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                {{ login_form.username(class='form-control', placeholder='Username') }}
                <span class="glyphicon form-control-feedback"></span>
              </div>
              <br>
              <br>
              <div class="input-group input-group-lg col-xs-10 col-xs-offset-1 has-feedback" data-toggle="tooltip"
                        data-placement="bottom" data-trigger="manual" title="Must be 7 characters or more">
                <span class="input-group-addon"><span class="glyphicon glyphicon-barcode"></span></span>
                {{ login_form.password(class='form-control', placeholder='Password') }}
                <span class="glyphicon form-control-feedback"></span>
              </div>
              <br>
              {{ login_form.csrf_token() }}
              <div class="alert alert-danger" role="alert">
                <p class="alert-message">Error Message Here</p>
              </div>
              <div class="button-div">
                <button id="login" class="btn btn-default col-xs-6 col-xs-offset-3" type="submit" disabled>
                  Submit
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endmacro %}

{% macro post(post_form) %}
  <div class="modal fade" id="post-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-title">
            Post
            <button type="button" class="close" data-dismiss="modal">
              <span>&times;</span>
            </button>
          </div>
        </div>
        <div class="modal-body">
          <form method="POST" id="post-form">
            <div class="form-group">
              {{ post_form.post_title.label }}
              <span id="title-count">100</span>
              {{ post_form.post_title(class='form-control') }}
              <br>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-primary active">
                  <input type="radio" name="options" id="option1" autocomplete="off" checked/>Public
                </label>
                <label class="btn btn-primary">
                  <input type="radio" name="options" id="option2" autocomplete="off"/>Private
                </label>
              </div>
              <br>
              <br>
              {{ post_form.post_text.label }}
              <span id="text-count">500</span>
              {{ post_form.post_text(type='text', class='form-control') }}
              {{ post_form.csrf_token() }}
              <br>
              <div class="alert alert-danger" id="post-alert" role="alert">
                <p class="alert-message">Error Message Here</p>
              </div>
              <div class="button-div">
                <button id="post-login" class="btn btn-default col-xs-6 col-xs-offset-3" type="submit" disabled>
                  Submit
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endmacro %}

{% macro comment(comment_form) %}
  <div class="modal fade" id="comment-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
          <div class="clearfix"></div>
          <div class="modal-title">
              <div id="original-rec">

              </div>
            </div>
          </div>
        <div class="modal-body">
          <form method="POST" id="comment-form">
            <div class="form-group">
              {{ comment_form.comment_text.label }}
              <span id="comment-count">250</span>
              {{ comment_form.comment_text(type='text', class='form-control') }}
              {{ comment_form.csrf_token() }}
              {{ comment_form.comment_id() }}
              <br>
              <div class="alert alert-danger" id="comment-alert" role="alert">
                <p class="alert-message">Error Message Here</p>
              </div>
              <div class="button-div">
                <button id="comment-login" class="btn btn-default col-xs-6 col-xs-offset-3" type="submit" disabled>
                  Submit
                </button>
              </div>
            </div>
          </form>
          <div id='comment-insert-point'>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endmacro %}

app/templates/macros/navbar.html
{% macro build() %}
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#collapsedNav">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <p class="navbar-brand">Rec Me App</p>
      </div>
      <div class="collapse navbar-collapse" id="collapsedNav">
        <ul class="nav navbar-nav">
          <li id='home-link'><a href="#">Home</a></li>
          <li id="post-link"><a href="#">Post</a></li>
          <li><a href="{{ url_for('main.logout') }}">Logout</a></li>
        </ul>
        <form id='search-form' class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
              <input id='search-bar' class="form-control" placeholder="Search")/>
            </div>
          </div>
        </form>
      </div>
    </div>
  </nav>
{% endmacro %}

app/templates/macros/render.html
{% macro render_recs(to_display, moment) %}
  <div class="container rec-container">
    <div class="row col-xs-offset-1 col-md-offset-0">
      {% for rec in to_display %}
        <div id="{{ rec['id'] }}" class="single-rec col-xs-10 col-md-6 col-lg-4">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <div class="panel-title lead">
                {{ rec['title'] }}
              </div>
              <span class="small text-uppercase"><span class="glyphicon glyphicon-user"></span> {{ rec['author'] }}</span>
              <span class="date">{{ moment(rec['timestamp']).fromNow() }} <span class="glyphicon glyphicon-calendar"></span></span>
            </div>
            <div class="panel-text">
                {{ rec['text'] }}
            </div>
            <a>
              <div class="panel-footer">
                <span class="badge">
                  <span class="badge-value">
                    {{ rec['comment_count'] }}
                  </span>
                  <span class="glyphicon glyphicon-comment"></span></span>
              </div>
            </a>
          </div>
        </div>
        {%  if loop.index % 2 == 0 %}
          <div class="clearfix visible-md-block"></div>
        {% endif %}
        {% if loop.index % 3 == 0 %}
          <div class="clearfix visible-lg-block"></div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro render_comments(to_display, moment) %}
  <div class="container-fluid comment-container">
    <div class="row">
      {% for comment in to_display %}
        {{ render_comment(comment, moment) }}
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro render_comment(comment, moment) %}
  <div class="single-comment col-xs-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <span class="small text-uppercase"><span class="glyphicon glyphicon-user"></span> {{ comment['author_username'] }}</span>
        <span class="date">{{ moment(comment['timestamp']).fromNow() }} <span class="glyphicon glyphicon-calendar"></span></span>
      </div>
      <div class="panel-text">
        {{ comment['text'] }}
      </div>
    </div>
  </div>
{% endmacro %}

app/templates/macros/render_recs.html
{% macro render_recs(to_display, moment) %}
  <div class="container rec-container">
    <div class="row col-xs-offset-1 col-md-offset-0">
      {% for rec in to_display %}
        <div id="{{ rec['id'] }}" class="single-rec col-xs-10 col-md-6 col-lg-4">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <div class="panel-title">
                {{ rec['title'] }}
              </div>
              <span class="small text-uppercase"><span class="glyphicon glyphicon-user"></span> {{ rec['author'] }}</span>
              <span class="date">{{ moment(rec['timestamp']).fromNow() }} <span class="glyphicon glyphicon-calendar"></span></span>
            </div>
            <div class="panel-text">
                {{ rec['text'] }}
            </div>
            <a>
              <div class="panel-footer">
                <span class="badge">
                  <span class="badge-value">
                    {{ rec['comment_count'] }}
                  </span>
                  <span class="glyphicon glyphicon-comment"></span></span>
              </div>
            </a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro render_comments(to_display, moment) %}
  <div class="container-fluid comment-container">
    <div class="row col-xs-offset-1">
      {% for comment in to_display %}
        {{ render_comment(comment, moment) }}
      {% endfor %}
    </div>
  </div>
{% endmacro %}

{% macro render_comment(comment, moment) %}
  <div class="single-comment col-xs-10">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <span class="small text-uppercase"><span class="glyphicon glyphicon-user"></span> {{ comment['author_username'] }}</span>
        <span class="date">{{ moment(comment['timestamp']).fromNow() }} <span class="glyphicon glyphicon-calendar"></span></span>
      </div>
      <div class="panel-text">
        {{ comment['text'] }}
      </div>
    </div>
  </div>
{% endmacro %}

app/templates/main/index.html
{% import 'macros/navbar.html' as navbar %}
{% import 'macros/modals.html' as modals %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Recommend Me App</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}"/>
  <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='fontawesome/css/font-awesome.min.css') }}" rel="stylesheet">
{#  <link href="{{ url_for('static', filename='css/main/index.less')}}" type="text/css" rel="stylesheet/less"/>#}
  <link href="{{ url_for('static', filename='css/main/index.min.css') }}" rel="stylesheet"/>
</head>
<body>
  {{ navbar.build() }}
  {{ modals.login(login_form) }}
  {{ modals.post(post_form) }}
  {{ modals.comment(comment_form) }}
  <div class="container-fluid">
    <div class="col-xs-12">
        <h1 class="welcome">Hello {{ session['user'] }}</h1>
    </div>
  </div>
  <div id='insert-point' class="container-fluid">
    <div class="col-xs-6 col-xs-offset-3">
      <button id='load-button' class="btn btn-info btn-block" disabled>
        <span id='load-icon'>
          <i class="fa fa-spinner fa-pulse fa3x"></i>
        </span>
        <span class="load-text">Load More</span>
      </button>
    </div>
  </div>
  <script>
    loginUrl = "{{ url_for('main.login') }}";
    logoutUrl = "{{ url_for('main.logout') }}";
    recUrl = "{{ url_for('main.recs_async') }}";
    postUrl = "{{ url_for('main.post_recs') }}";
    searchUrl = "{{ url_for('main.recs_async_begin') }}";
    commentUrl = "{{ url_for('main.comments_get') }}";
    postCommentUrl = "{{ url_for('main.post_comments') }}";
    id = "{{ id }}";
    user = "{{ session['user'] }}";
  </script>
  {{ moment.include_jquery() }}
  {{ moment.include_moment() }}
  <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/main/login.js') }}"></script>
  <script src="{{ url_for('static', filename='js/main/post.js') }}"></script>
  <script src="{{ url_for('static', filename='js/main/navigate.js') }}"></script>
  <script src="{{ url_for('static', filename='js/main/ajaxCalls.js') }}"></script>
  <script src="{{ url_for('static', filename='js/main/comment.js') }}"></script>
{#  <script src="{{ url_for('static', filename='js/less/less.min.js') }}" type="text/javascript"></script>#}
</body>
</html>